browser=chrome
url=https://www.saucedemo.com
#happy path user
username=standard_user
#login failure user
locked_username=locked_out_user
#functional and UI bugs
problem_username=problem_user
#slow performance user
performance_glitch_username=performance_glitch_user
#certain actions trigger failure
error_username=error_user
#Visual cosmetic or layout defects
visual_username=visual_user

password=secret_sauce

implicitWait=10
pageLoadTimeout=20